"use server";

import prisma from "@/lib/db";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

// ─── Submit Feedback ────────────────────────────────────────
// Called from the review card / detail page when user clicks 👍👎❌💡
export async function submitFeedback(
  reviewId: string,
  section: string,
  reaction: string,
  comment?: string
) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user?.id) throw new Error("Unauthorized");

  // Sanitize inputs — never inject raw user text into prompts without this
  const allowedSections = ["issues", "summary", "risk", "overall"];
  const allowedReactions = ["helpful", "unhelpful", "incorrect", "want_more"];

  if (!allowedSections.includes(section)) throw new Error("Invalid section");
  if (!allowedReactions.includes(reaction)) throw new Error("Invalid reaction");

  // Ensure the review belongs to the current user
  const review = await prisma.review.findFirst({
    where: {
      id: reviewId,
      repository: { userId: session.user.id },
    },
    select: { id: true },
  });
  if (!review) throw new Error("Review not found");

  // Upsert: one reaction per user per section per review
  const sanitizeComment = (raw: string) =>
    raw
      .replace(/[<>{}[\]]/g, "")         // Strip HTML/template characters
      .replace(/```/g, "")               // Strip code fences that could break prompt formatting
      .replace(/\r?\n{3,}/g, "\n\n")     // Collapse excessive newlines
      .trim()
      .slice(0, 500);

  await prisma.reviewFeedback.upsert({
    where: {
      reviewId_userId_section: {
        reviewId,
        userId: session.user.id,
        section,
      },
    },
    create: {
      reviewId,
      userId: session.user.id,
      section,
      reaction,
      comment: comment ? sanitizeComment(comment) : null,
    },
    update: {
      reaction,
      comment: comment ? sanitizeComment(comment) : null,
    },
  });

  return { success: true };
}

// ─── Get Feedback for a Review ──────────────────────────────
// Used to show which buttons are already selected in the UI
export async function getFeedbackForReview(reviewId: string) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user?.id) throw new Error("Unauthorized");

  const feedbacks = await prisma.reviewFeedback.findMany({
    where: {
      reviewId,
      userId: session.user.id,
    },
    select: {
      section: true,
      reaction: true,
    },
  });

  // Return as a map: section → reaction for easy lookup in UI
  return Object.fromEntries(feedbacks.map((f) => [f.section, f.reaction])) as Record<
    string,
    string
  >;
}

// ─── Get Feedback Context for Prompt Injection ──────────────
// Called by the Inngest review job to get hints for this repo
export async function getFeedbackPromptContext(
  repositoryId: string
): Promise<string> {
  const aggregations = await prisma.feedbackAggregation.findMany({
    where: { repositoryId },
    orderBy: { accuracy: "desc" },
  });

  if (aggregations.length === 0) return "";

  const hints = aggregations
    .filter((a) => a.totalCount >= 3)
    .flatMap((a) => a.promptHints)
    .slice(0, 5); // cap at 5 hints to stay within token budget

  if (hints.length === 0) return "";

  // Sanitize before prompt injection — hints are generated by our own code
  // but we defensively strip anything that looks like prompt injection
  const safeHints = hints
    .map((h) => h.replace(/\n/g, " ").trim())
    .filter((h) => h.length > 0 && h.length < 300);

  return safeHints.length > 0
    ? `\nTEAM FEEDBACK CONTEXT (learned from previous reviews on this repo):\n${safeHints.map((h) => `- ${h}`).join("\n")}`
    : "";
}
